### ISSUE TITLE
persistent q across session and across reboots ?

### ISSUE THREAD

**Issue by hubgitname** [cal2195/q#4]
Hi, 

Nice plugin!
Is it possible to have the registers persistent across reboot and across shells ?

Thanks.

**Comment by cal2195** [comment]
Hi there!

This should already be the case, provided your using the same user! 🙂

Is it not working for you?

**Comment by hubgitname** [comment]
oh...I tried it from scratch and it now works. Not sure what I did wrong last time.
Two suggestions if I may: 
1) the name q is not searchable, can you rename it to something like zsh-registers.
2) can you change the manual install to something more  copy/pastable like so:
"clone https://github.com/popstas/q.git ~/.oh-my-zsh/custom/plugins/q
And add "q" without quotes to plugins in .zshrc"

This is a useful feature and I'd like to see it adopted widely.

**Comment by hubgitname** [comment]
Other than this, all seems to be good now. I'll close this issue.
